/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Controleur;

import Modele.*;
import Affichage.*;
import java.text.NumberFormat;
import javax.swing.JFormattedTextField;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.NumberFormatter;

/**
 *
 * @author pierr
 */
public class Graphique extends javax.swing.JFrame {
    private Ecole ecole;
    private Affichage A;
    private Controleur C;
    private Personne personneCo;
    private int selectedEleveID;
    private int selectedInscriptionID;
    
    /**
     * Creates new form Graphique
     */
    public Graphique() {
        this.ecole = new Ecole();
        this.A = new Affichage();
        this.C = new Controleur();
        this.selectedEleveID = 0;
        this.selectedInscriptionID = 0;

        
        initComponents();
        A.afficherElevesJTable(tabEleves, this.ecole.getEleves());
    }
    
    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBase = new javax.swing.JPanel();
        srcEleveButton = new javax.swing.JButton();
        fieldSrcEleve = new javax.swing.JFormattedTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabEleves = new javax.swing.JTable();
        helloLabel = new javax.swing.JLabel();
        nomLabel = new javax.swing.JLabel();
        profilButton = new javax.swing.JButton();
        myProfilButton = new javax.swing.JButton();
        profButton = new javax.swing.JButton();
        directeurButton = new javax.swing.JButton();
        deconnexionButton = new javax.swing.JButton();
        panelConnexion = new javax.swing.JPanel();
        labelIDConnexion = new javax.swing.JLabel();
        connexionButton = new javax.swing.JButton();
        fieldIDConnexion = new javax.swing.JFormattedTextField();
        coFailLabel = new javax.swing.JLabel();
        profilPanel = new javax.swing.JPanel();
        profilLabel = new javax.swing.JLabel();
        nomPrenomProfilLabel = new javax.swing.JLabel();
        prenomProfilLabel = new javax.swing.JLabel();
        nomProfilLabel = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabInscription = new javax.swing.JTable();
        bulletinButton = new javax.swing.JButton();
        backListeElvButton = new javax.swing.JButton();
        bulletinPanel = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabBulletin = new javax.swing.JTable();
        detailButton = new javax.swing.JButton();
        backProfilButton = new javax.swing.JButton();
        detailPanel = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tabDetail = new javax.swing.JTable();
        ajouterNoteButton = new javax.swing.JButton();
        modifNoteButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        //panelBase.setVisible(false);

        srcEleveButton.setText("Rechercher");
        srcEleveButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                srcEleveButtonMouseClicked(evt);
            }
        });

        tabEleves.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Identifiant", "Nom", "Prenom"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tabEleves.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabElevesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabEleves);

        helloLabel.setText("Bienvenue, ");

        nomLabel.setText("nomLabel");

        profilButton.setText("Voir Profil");
        profilButton.setEnabled(false);
        profilButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                profilButtonMouseClicked(evt);
            }
        });

        myProfilButton.setText("Mon Profil");

        profButton.setText("Voir Enseignants");

        directeurButton.setText("Directeur stuff");
        directeurButton.setEnabled(false);

        deconnexionButton.setText("Deconnexion");
        deconnexionButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deconnexionButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelBaseLayout = new javax.swing.GroupLayout(panelBase);
        panelBase.setLayout(panelBaseLayout);
        panelBaseLayout.setHorizontalGroup(
            panelBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBaseLayout.createSequentialGroup()
                .addGroup(panelBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelBaseLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(helloLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nomLabel))
                    .addGroup(panelBaseLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(panelBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelBaseLayout.createSequentialGroup()
                                .addGroup(panelBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(fieldSrcEleve, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(panelBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(profButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(profilButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(srcEleveButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(myProfilButton))
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelBaseLayout.createSequentialGroup()
                                .addComponent(directeurButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(deconnexionButton)))))
                .addGap(18, 18, 18))
        );
        panelBaseLayout.setVerticalGroup(
            panelBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBaseLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(helloLabel)
                    .addComponent(nomLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panelBaseLayout.createSequentialGroup()
                        .addComponent(fieldSrcEleve, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(srcEleveButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(profilButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(profButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(myProfilButton))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(directeurButton)
                    .addComponent(deconnexionButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        labelIDConnexion.setText("Identifiant");

        connexionButton.setText("Connexion");
        connexionButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                connexionButtonMouseClicked(evt);
            }
        });

        coFailLabel.setText("Connexion Echouee");
        coFailLabel.setVisible(false);

        javax.swing.GroupLayout panelConnexionLayout = new javax.swing.GroupLayout(panelConnexion);
        panelConnexion.setLayout(panelConnexionLayout);
        panelConnexionLayout.setHorizontalGroup(
            panelConnexionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelConnexionLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(panelConnexionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(coFailLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelConnexionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(connexionButton)
                        .addGroup(panelConnexionLayout.createSequentialGroup()
                            .addComponent(labelIDConnexion)
                            .addGap(18, 18, 18)
                            .addComponent(fieldIDConnexion, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        panelConnexionLayout.setVerticalGroup(
            panelConnexionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelConnexionLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(panelConnexionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelIDConnexion)
                    .addComponent(fieldIDConnexion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(connexionButton)
                .addGap(18, 18, 18)
                .addComponent(coFailLabel)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        profilLabel.setText("Profil de");

        nomPrenomProfilLabel.setText("nomPrenomProfilLabel");

        prenomProfilLabel.setText("Prenom");

        nomProfilLabel.setText("Nom");

        tabInscription.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Inscription", "Classe Inscrite", "Annee Classe", "Niveau"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tabInscription.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabInscriptionMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabInscription);

        bulletinButton.setText("Voir Bulletins");
        bulletinButton.setEnabled(false);
        bulletinButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bulletinButtonMouseClicked(evt);
            }
        });

        backListeElvButton.setText("Retour Liste Eleve");
        backListeElvButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backListeElvButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout profilPanelLayout = new javax.swing.GroupLayout(profilPanel);
        profilPanel.setLayout(profilPanelLayout);
        profilPanelLayout.setHorizontalGroup(
            profilPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(profilPanelLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(profilPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(profilPanelLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(profilPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(backListeElvButton)
                            .addComponent(bulletinButton))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(profilPanelLayout.createSequentialGroup()
                        .addGroup(profilPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(profilLabel)
                            .addGroup(profilPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(nomProfilLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(prenomProfilLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nomPrenomProfilLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        profilPanelLayout.setVerticalGroup(
            profilPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(profilPanelLayout.createSequentialGroup()
                .addGroup(profilPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(profilPanelLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(profilPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(profilLabel)
                            .addComponent(nomPrenomProfilLabel))
                        .addGap(40, 40, 40)
                        .addComponent(prenomProfilLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nomProfilLabel))
                    .addGroup(profilPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(bulletinButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(backListeElvButton)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        tabBulletin.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Bulletin", "Trimestre", "Moyenne Generale", "Appreciation"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.Double.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tabBulletin);

        detailButton.setText("Voir Details");

        backProfilButton.setText("Retour Profil");
        backProfilButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backProfilButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout bulletinPanelLayout = new javax.swing.GroupLayout(bulletinPanel);
        bulletinPanel.setLayout(bulletinPanelLayout);
        bulletinPanelLayout.setHorizontalGroup(
            bulletinPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bulletinPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(bulletinPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(detailButton)
                    .addComponent(backProfilButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(371, 371, 371))
        );
        bulletinPanelLayout.setVerticalGroup(
            bulletinPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bulletinPanelLayout.createSequentialGroup()
                .addGroup(bulletinPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bulletinPanelLayout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(detailButton)
                        .addGap(18, 18, 18)
                        .addComponent(backProfilButton))
                    .addGroup(bulletinPanelLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(66, Short.MAX_VALUE))
        );

        tabDetail.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Enseignement", "Moyenne", "Coefficient", "Appreciation"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Double.class, java.lang.Integer.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane4.setViewportView(tabDetail);

        ajouterNoteButton.setText("Ajouter Note");

        modifNoteButton.setText("Modifier Note");

        javax.swing.GroupLayout detailPanelLayout = new javax.swing.GroupLayout(detailPanel);
        detailPanel.setLayout(detailPanelLayout);
        detailPanelLayout.setHorizontalGroup(
            detailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(detailPanelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(detailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ajouterNoteButton)
                    .addComponent(modifNoteButton))
                .addGap(42, 42, 42)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        detailPanelLayout.setVerticalGroup(
            detailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(detailPanelLayout.createSequentialGroup()
                .addGroup(detailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(detailPanelLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(detailPanelLayout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(ajouterNoteButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(modifNoteButton)))
                .addContainerGap(105, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(profilPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelBase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelConnexion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bulletinPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(detailPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(1229, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panelBase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(profilPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(190, 190, 190))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(panelConnexion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                        .addComponent(detailPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bulletinPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(147, 147, 147))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void srcEleveButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_srcEleveButtonMouseClicked
        // TODO add your handling code here:
        String text = fieldSrcEleve.getText();
        System.out.println(text);
        int ID = C.stringToInt(text);
        Eleve elv = new Eleve(C.elevesSearchByID(ID, ecole.getEleves()));
        if (ID != 0) A.afficherSingleEleveJTable(tabEleves, elv);
        else A.afficherElevesJTable(tabEleves, ecole.getEleves());
    }//GEN-LAST:event_srcEleveButtonMouseClicked

    private void connexionButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_connexionButtonMouseClicked
        // TODO add your handling code here:
        String text = fieldIDConnexion.getText();
        int ID = C.stringToInt(text);
        Personne P = C.connexionSearch(ID, ecole.getEleves(), ecole.getEnseignants(), ecole.getDirecteurs());
        if (P != null) {
            coFailLabel.setVisible(false);
            panelConnexion.setVisible(false);
            panelBase.setVisible(true);
            this.personneCo = P;
            nomLabel.setText(personneCo.getPrenom() + " " + personneCo.getNom());
            if (personneCo.getAcces() == 2) { directeurButton.setEnabled(true); }
        }
        else coFailLabel.setVisible(true);
    }//GEN-LAST:event_connexionButtonMouseClicked

    private void profilButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_profilButtonMouseClicked
        // TODO add your handling code here:
        String prenom = ecole.getEleves().get(this.selectedEleveID).getPrenom();
        String nom = ecole.getEleves().get(this.selectedEleveID).getNom();
        
        panelBase.setVisible(false);
        profilPanel.setVisible(true);
        prenomProfilLabel.setText(prenom);
        nomProfilLabel.setText(nom);
        nomPrenomProfilLabel.setText(nom + " " + prenom);
        
        A.afficherClassesInscritesEleve(tabInscription, ecole.getEleves().get(this.selectedEleveID), ecole.getNiveaux());
    }//GEN-LAST:event_profilButtonMouseClicked

    private void tabElevesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabElevesMouseClicked
        // TODO add your handling code here:
        this.selectedEleveID = (int) tabEleves.getValueAt(tabEleves.getSelectedRow(), 0);
        profilButton.setEnabled(true);
    }//GEN-LAST:event_tabElevesMouseClicked

    private void backListeElvButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backListeElvButtonMouseClicked
        // TODO add your handling code here:
        panelBase.setVisible(true);
        profilPanel.setVisible(false);
        bulletinButton.setEnabled(false);
    }//GEN-LAST:event_backListeElvButtonMouseClicked

    private void tabInscriptionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabInscriptionMouseClicked
        // TODO add your handling code here:
        this.selectedInscriptionID = (int) tabEleves.getValueAt(tabEleves.getSelectedRow(), 0);
        bulletinButton.setEnabled(true);
    }//GEN-LAST:event_tabInscriptionMouseClicked

    private void deconnexionButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deconnexionButtonMouseClicked
        // TODO add your handling code here:
        this.personneCo = null;
        panelConnexion.setVisible(true);
        directeurButton.setEnabled(false);
    }//GEN-LAST:event_deconnexionButtonMouseClicked

    private void bulletinButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bulletinButtonMouseClicked
        // TODO add your handling code here:
        
        profilPanel.setVisible(false);
        bulletinPanel.setVisible(true);
        
        A.afficherBulletinsInscription(tabBulletin, ecole.getEleves().get(this.selectedEleveID).getInscriptions().get(this.selectedInscriptionID), ecole.getAnnees());
    }//GEN-LAST:event_bulletinButtonMouseClicked

    private void backProfilButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backProfilButtonMouseClicked
        // TODO add your handling code here:
        profilPanel.setVisible(true);
    }//GEN-LAST:event_backProfilButtonMouseClicked

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Graphique.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Graphique.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Graphique.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Graphique.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Graphique().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ajouterNoteButton;
    private javax.swing.JButton backListeElvButton;
    private javax.swing.JButton backProfilButton;
    private javax.swing.JButton bulletinButton;
    private javax.swing.JPanel bulletinPanel;
    private javax.swing.JLabel coFailLabel;
    private javax.swing.JButton connexionButton;
    private javax.swing.JButton deconnexionButton;
    private javax.swing.JButton detailButton;
    private javax.swing.JPanel detailPanel;
    private javax.swing.JButton directeurButton;
    private javax.swing.JFormattedTextField fieldIDConnexion;
    private javax.swing.JFormattedTextField fieldSrcEleve;
    private javax.swing.JLabel helloLabel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel labelIDConnexion;
    private javax.swing.JButton modifNoteButton;
    private javax.swing.JButton myProfilButton;
    private javax.swing.JLabel nomLabel;
    private javax.swing.JLabel nomPrenomProfilLabel;
    private javax.swing.JLabel nomProfilLabel;
    private javax.swing.JPanel panelBase;
    private javax.swing.JPanel panelConnexion;
    private javax.swing.JLabel prenomProfilLabel;
    private javax.swing.JButton profButton;
    private javax.swing.JButton profilButton;
    private javax.swing.JLabel profilLabel;
    private javax.swing.JPanel profilPanel;
    private javax.swing.JButton srcEleveButton;
    private javax.swing.JTable tabBulletin;
    private javax.swing.JTable tabDetail;
    private javax.swing.JTable tabEleves;
    private javax.swing.JTable tabInscription;
    // End of variables declaration//GEN-END:variables
}
